//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUpDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class jouet
    {
        public int id1 { get; set; }
        public string nom1 { get; set; }
        public string type1 { get; set; }
        public int agemin1 { get; set; }
        public int agemax1 { get; set; }
        public string photo1 { get; set; }
        public double prix1 { get; set; }
        public int id_fournisseur1 { get; set; }
        public int stock1 { get; set; }
    }
}
